spring.application.name=FileProcessing

spring.datasource.url=jdbc:mysql://localhost:3306/file_processing_db
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# file path
file.upload-dir=converter/in/
file.transaction.header=transaction_id,account_number,amount,currency,status
file.customer.header=customer_id,customer_name,email,status

